### ISSUE TITLE
Installing a plugin when using docker

### ISSUE THREAD

**Issue by Vanger69** [woolfg/dokuwiki-plugin-gitbacked#97]
**Problem:** I have DokuWiki running in Docker. When I try to install a plugin, I can't get it to work with GitLab (self-hosted). The documentation doesn't provide detailed installation steps, so I want to check if I'm doing everything correctly.

**Versions:**
* Dokuwiki - **Release 2024-02-06b "Kaos"**
* gitbacked Plugin - **version is from 2025-02-26**

**How I installed DokuWiki + gitbacked** (fresh installation):
1. The working directory for DokuWiki on the host contains **docker-compose.yaml** file and **./storage** folder, which is mounted into container.
2. **./storage** folder is created using `mkdir ./storage`. -> I set permissions with `chown -R 33:33 ./storage` and `chmod -R 755 ./storage`.
2. `docker compose up -d` . Contents of the docker-compose.yaml file:
```
services:
  dokuwiki:
    image: dokuwiki/dokuwiki:stable # other tags: master, <date> or <codename>
#    user: "1000:1000" # adjust to your required user id
    restart: unless-stopped
    ports:
      - "8080:8080" # internal port is 8080, map to what you need
    environment:
      PHP_TIMEZONE: Europe/London
      #PHP_MEMORYLIMIT: 256M
      #PHP_UPLOADLIMIT: 128M
    volumes:
      - ./storage:/storage
```
4. I go to **1.2.3.4:8080/install.php** and complete basic setup. -> Then I install gitbacked plugin **through plugin manager in admin panel**.
5. In plugin settings (UI), in **plugin»gitbacked»repoPath**, I set value to **./data/gitrepo** .
6. Further configuration is done from **dokuwiki container**. 
`docker compose exec dokuwiki bash`
`apt update && apt install git`
`mkdir -p /var/www/html/data/gitrepo/wiki/pages`
`mkdir -p /var/www/html/data/gitrepo/wiki/media`
7. I add following lines to **./config/local.php**:
```
$conf['datadir'] = './data/gitrepo/wiki/pages';
$conf['mediadir'] = './data/gitrepo/wiki/media';
```
8. I assign ownership of **/var/www** directory to **www-data** to ensure Git works correctly (and just in case):
```
chown 33:33 -R /var/www/
chmod -R 755 /var/www/
```
9. Now, I configure Git under **www-data** user:
```
su -s /bin/bash www-data
git config --global credential.helper
cd /var/www/html/data/gitrepo
git add .
git commit -m "Initial commit"
git config --global user.name "wiki"
git config --global user.email "wiki@test.com"
git remote add origin https://gitlab.repo.uk/repo/wiki.git
git push -u origin main
```
10. I entered login and token for service account. A next **git push** works without asking for a password.
11. On dokuwiki web-site, In plugin settings (UI), in **plugin»gitbacked»periodicPull**, I set tick. And in **plugin»gitbacked»periodicMinutes** - 5 . Click **save**.

**Result:** An error appears at the bottom of the page.

> DokuWiki Setup Error
> 
> Something unforeseen has happened: Git committing or pushing failed: fatal: could not read Username for 'https://gitlab.planet9.uk'

I’d really appreciate any guidance to help me understand what I might be doing wrong.
